import type { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import { Inter } from "next/font/google";
import Header from "./components/header/page";
import GlobalStyle from "./globals";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Доски | ilyask",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <StyledComponentsRegistry>
                    <GlobalStyle />
                    <>
                        <Header />
                        {children}
                    </>
                </StyledComponentsRegistry>
            </body>
        </html>
    );
}
