import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/header/page";
import { DivWrapChildrenSC, DivWrapperSC, GlobalStyle } from "./globals";
import ThemeProviderComp from "./themeProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Доски | ilyask",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProviderComp>
                    <GlobalStyle />
                    <DivWrapperSC>
                        <Header />
                        <DivWrapChildrenSC>{children}</DivWrapChildrenSC>
                    </DivWrapperSC>
                </ThemeProviderComp>
            </body>
        </html>
    );
}
